backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "hero" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Button Text", name: "buttonText", widget: "string" }
              - { label: "Button URL", name: "buttonUrl", widget: "string" }
          
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "about" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          
          - label: "Areas Section"
            name: "areas"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "areas" }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Areas"
                name: "areas"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
          
          - label: "Mission Section"
            name: "mission"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "mission" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
              - label: "Values"
                name: "values"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
          
          - label: "Team Section"
            name: "team"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "team" }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Members"
                name: "members"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Role", name: "role", widget: "string" }
                  - { label: "Bio", name: "bio", widget: "markdown" }
          
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "contact" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
